# Railway-specific deployment configuration

[build]
provider = "docker"
dockerfilePath = "docker/Dockerfile"

[deploy]
startCommand = "cd app && .\run.bat"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3