# Railway-specific deployment configuration

[build]
provider = "docker"
dockerfilePath = "docker/Dockerfile"

[deploy]
startCommand = "./app/run.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3